// server/seed/data.js
//
// Realistic seed data for the graph: well-known tabletop games with their
// real designers, publishers, mechanics and categories, plus a handful of
// demo "players" with ratings so the recommendation queries have something
// to traverse. Facts (names, years, player counts) are public knowledge;
// descriptions are written for this project.

const games = [
  { title: "Catan", year: 1995, minPlayers: 3, maxPlayers: 4, playTime: 90, complexity: 2.3,
    description: "Trade sheep for bricks, build roads, and try not to get boxed in by your neighbours.",
    designers: ["Klaus Teuber"], publisher: "Kosmos",
    mechanics: ["Trading", "Dice Rolling", "Route Building", "Hand Management"],
    categories: ["Strategy", "Family"] },
  { title: "Pandemic", year: 2008, minPlayers: 2, maxPlayers: 4, playTime: 45, complexity: 2.4,
    description: "A cooperative race to cure four diseases before they overrun the globe.",
    designers: ["Matt Leacock"], publisher: "Z-Man Games",
    mechanics: ["Cooperative Play", "Hand Management", "Set Collection", "Point-to-Point Movement"],
    categories: ["Strategy", "Cooperative"] },
  { title: "Carcassonne", year: 2000, minPlayers: 2, maxPlayers: 5, playTime: 40, complexity: 1.9,
    description: "Lay tiles to grow a medieval landscape and claim cities, roads and cloisters with your meeples.",
    designers: ["Klaus-Jürgen Wrede"], publisher: "Hans im Glück",
    mechanics: ["Tile Placement", "Area Control", "Scoring Bonuses"],
    categories: ["Family", "Strategy"] },
  { title: "Ticket to Ride", year: 2004, minPlayers: 2, maxPlayers: 5, playTime: 60, complexity: 1.8,
    description: "Collect coloured train cards and race to connect cities across the map.",
    designers: ["Alan R. Moon"], publisher: "Days of Wonder",
    mechanics: ["Route Building", "Set Collection", "Hand Management"],
    categories: ["Family", "Strategy"] },
  { title: "7 Wonders", year: 2010, minPlayers: 3, maxPlayers: 7, playTime: 30, complexity: 2.3,
    description: "Draft cards to build up an ancient civilisation over three ages, passing your hand around the table.",
    designers: ["Antoine Bauza"], publisher: "Repos Production",
    mechanics: ["Drafting", "Set Collection", "Simultaneous Action Selection"],
    categories: ["Strategy", "Card Game"] },
  { title: "Splendor", year: 2014, minPlayers: 2, maxPlayers: 4, playTime: 30, complexity: 1.8,
    description: "Collect gem tokens to buy development cards and race to 15 prestige points.",
    designers: ["Marc André"], publisher: "Space Cowboys",
    mechanics: ["Engine Building", "Set Collection", "Hand Management"],
    categories: ["Strategy", "Family"] },
  { title: "Azul", year: 2017, minPlayers: 2, maxPlayers: 4, playTime: 40, complexity: 1.8,
    description: "Draft coloured tiles to decorate the walls of a Portuguese palace without wasting a single piece.",
    designers: ["Michael Kiesling"], publisher: "Plan B Games",
    mechanics: ["Drafting", "Tile Placement", "Pattern Building"],
    categories: ["Family", "Abstract Strategy"] },
  { title: "Wingspan", year: 2019, minPlayers: 1, maxPlayers: 5, playTime: 70, complexity: 2.4,
    description: "Attract birds to a network of wildlife preserves in this engine-building game about ornithology.",
    designers: ["Elizabeth Hargrave"], publisher: "Stonemaier Games",
    mechanics: ["Engine Building", "Set Collection", "Hand Management"],
    categories: ["Strategy", "Card Game"] },
  { title: "Terraforming Mars", year: 2016, minPlayers: 1, maxPlayers: 5, playTime: 120, complexity: 3.2,
    description: "Corporations compete to raise Mars's temperature, oxygen and oceans while building an economic engine.",
    designers: ["Jacob Fryxelius"], publisher: "FryxGames",
    mechanics: ["Engine Building", "Tile Placement", "Hand Management", "Variable Player Powers"],
    categories: ["Strategy", "Science Fiction"] },
  { title: "Gloomhaven", year: 2017, minPlayers: 1, maxPlayers: 4, playTime: 120, complexity: 3.9,
    description: "A campaign of tactical dungeon-crawling battles with a persistent, evolving story.",
    designers: ["Isaac Childres"], publisher: "Cephalofair Games",
    mechanics: ["Hand Management", "Cooperative Play", "Grid Movement", "Legacy Game"],
    categories: ["Strategy", "Cooperative", "Adventure"] },
  { title: "Codenames", year: 2015, minPlayers: 2, maxPlayers: 8, playTime: 15, complexity: 1.3,
    description: "Give one-word clues to help your team guess your agents' identities before the other side does.",
    designers: ["Vlaada Chvátil"], publisher: "Czech Games Edition",
    mechanics: ["Team-Based Play", "Word Guessing", "Deduction"],
    categories: ["Party", "Word Game"] },
  { title: "Dixit", year: 2008, minPlayers: 3, maxPlayers: 6, playTime: 30, complexity: 1.2,
    description: "Give a poetic clue for a surreal card and see who can guess it — without making it too obvious.",
    designers: ["Jean-Louis Roubira"], publisher: "Libellud",
    mechanics: ["Storytelling", "Voting", "Hand Management"],
    categories: ["Party", "Card Game"] },
  { title: "Concordia", year: 2013, minPlayers: 2, maxPlayers: 5, playTime: 100, complexity: 3.0,
    description: "Build trade routes across the Roman Empire by carefully sequencing a small hand of role cards.",
    designers: ["Mac Gerdts"], publisher: "PD-Verlag",
    mechanics: ["Route Building", "Hand Management", "Engine Building"],
    categories: ["Strategy"] },
  { title: "Brass: Birmingham", year: 2018, minPlayers: 2, maxPlayers: 4, playTime: 120, complexity: 3.9,
    description: "Build canal and rail networks and industries across two eras of the Industrial Revolution.",
    designers: ["Gavan Brown", "Matt Tolman", "Martin Wallace"], publisher: "Roxley Games",
    mechanics: ["Route Building", "Engine Building", "Hand Management"],
    categories: ["Strategy", "Economic"] },
  { title: "Puerto Rico", year: 2002, minPlayers: 2, maxPlayers: 5, playTime: 120, complexity: 3.3,
    description: "Choose a role each round to grow plantations, ship goods and build a colonial economy.",
    designers: ["Andreas Seyfarth"], publisher: "Ravensburger",
    mechanics: ["Variable Player Powers", "Engine Building", "Hand Management"],
    categories: ["Strategy", "Economic"] },
  { title: "Agricola", year: 2007, minPlayers: 1, maxPlayers: 5, playTime: 120, complexity: 3.6,
    description: "Grow crops, raise animals and expand a small farmhouse before the harvest catches up with you.",
    designers: ["Uwe Rosenberg"], publisher: "Lookout Games",
    mechanics: ["Worker Placement", "Hand Management", "Set Collection"],
    categories: ["Strategy", "Economic"] },
  { title: "Caverna", year: 2013, minPlayers: 1, maxPlayers: 7, playTime: 150, complexity: 3.6,
    description: "Expand a dwarven cave system through farming, mining and adventuring.",
    designers: ["Uwe Rosenberg"], publisher: "Lookout Games",
    mechanics: ["Worker Placement", "Hand Management", "Set Collection"],
    categories: ["Strategy", "Economic"] },
  { title: "Patchwork", year: 2014, minPlayers: 2, maxPlayers: 2, playTime: 30, complexity: 1.6,
    description: "Piece together fabric scraps on a personal quilt board while racing a shared time track.",
    designers: ["Uwe Rosenberg"], publisher: "Lookout Games",
    mechanics: ["Tile Placement", "Pattern Building"],
    categories: ["Abstract Strategy", "Family"] },
  { title: "Scythe", year: 2016, minPlayers: 1, maxPlayers: 5, playTime: 115, complexity: 3.4,
    description: "Alternate-history factions expand across a war-torn Europa using mechs, workers and resources.",
    designers: ["Jamey Stegmaier"], publisher: "Stonemaier Games",
    mechanics: ["Variable Player Powers", "Area Control", "Engine Building"],
    categories: ["Strategy", "Science Fiction"] },
  { title: "Root", year: 2018, minPlayers: 2, maxPlayers: 4, playTime: 90, complexity: 3.1,
    description: "Asymmetric woodland factions fight for control of a forest, each playing by entirely different rules.",
    designers: ["Cole Wehrle"], publisher: "Leder Games",
    mechanics: ["Variable Player Powers", "Area Control", "Asymmetric Abilities"],
    categories: ["Strategy", "Wargame"] },
  { title: "Everdell", year: 2018, minPlayers: 1, maxPlayers: 4, playTime: 80, complexity: 2.7,
    description: "Woodland critters build a city among the roots of a great tree across four seasons.",
    designers: ["James A. Wilson"], publisher: "Starling Games",
    mechanics: ["Worker Placement", "Tableau Building", "Set Collection"],
    categories: ["Strategy", "Card Game"] },
  { title: "Viticulture", year: 2013, minPlayers: 1, maxPlayers: 6, playTime: 90, complexity: 2.9,
    description: "Manage a Tuscan vineyard, from planting vines to fulfilling wine orders.",
    designers: ["Jamey Stegmaier", "Alan Stone"], publisher: "Stonemaier Games",
    mechanics: ["Worker Placement", "Hand Management"],
    categories: ["Strategy", "Economic"] },
  { title: "Tzolk'in: The Mayan Calendar", year: 2012, minPlayers: 2, maxPlayers: 4, playTime: 90, complexity: 3.4,
    description: "Place workers on interlocking gears that turn every round, changing what each action yields.",
    designers: ["Simone Luciani", "Daniele Tascini"], publisher: "Czech Games Edition",
    mechanics: ["Worker Placement", "Engine Building"],
    categories: ["Strategy"] },
  { title: "Century: Spice Road", year: 2017, minPlayers: 2, maxPlayers: 5, playTime: 40, complexity: 1.8,
    description: "Trade and upgrade spices along a caravan route in a lean, engine-building card game.",
    designers: ["Emerson Matsuuchi"], publisher: "Plan B Games",
    mechanics: ["Engine Building", "Hand Management", "Set Collection"],
    categories: ["Strategy", "Card Game"] },
  { title: "Star Realms", year: 2014, minPlayers: 2, maxPlayers: 2, playTime: 20, complexity: 2.0,
    description: "Duel with a shared trade deck, building a fleet of ships and bases to blast your opponent's authority to zero.",
    designers: ["Robert Dougherty", "Darwin Kastle"], publisher: "White Wizard Games",
    mechanics: ["Deck Building", "Hand Management"],
    categories: ["Strategy", "Science Fiction", "Card Game"] },
  { title: "Dominion", year: 2008, minPlayers: 2, maxPlayers: 4, playTime: 30, complexity: 2.4,
    description: "The game that invented deck-building: buy cards to improve your deck and out-tempo your rivals.",
    designers: ["Donald X. Vaccarino"], publisher: "Rio Grande Games",
    mechanics: ["Deck Building", "Hand Management"],
    categories: ["Strategy", "Card Game"] },
  { title: "Clank!", year: 2016, minPlayers: 2, maxPlayers: 4, playTime: 60, complexity: 2.2,
    description: "Deck-build your way into a dragon's dungeon, grab treasure, and sneak out before the dragon wakes.",
    designers: ["Paul Dennen"], publisher: "Renegade Game Studios",
    mechanics: ["Deck Building", "Push Your Luck", "Grid Movement"],
    categories: ["Strategy", "Adventure", "Card Game"] },
  { title: "Spirit Island", year: 2017, minPlayers: 1, maxPlayers: 4, playTime: 120, complexity: 4.0,
    description: "Cooperative spirits defend their island from colonising invaders using combinable elemental powers.",
    designers: ["R. Eric Reuss"], publisher: "Greater Than Games",
    mechanics: ["Cooperative Play", "Variable Player Powers", "Area Control", "Hand Management"],
    categories: ["Strategy", "Cooperative"] },
  { title: "Hanabi", year: 2010, minPlayers: 2, maxPlayers: 5, playTime: 25, complexity: 1.8,
    description: "A cooperative card game where you can see everyone's hand but your own — and must give clues carefully.",
    designers: ["Antoine Bauza"], publisher: "R&R Games",
    mechanics: ["Cooperative Play", "Hand Management", "Hidden Information"],
    categories: ["Cooperative", "Card Game"] },
  { title: "The Crew: The Quest for Planet Nine", year: 2019, minPlayers: 2, maxPlayers: 5, playTime: 20, complexity: 1.9,
    description: "A cooperative trick-taking game where the crew silently coordinates to complete space missions.",
    designers: ["Thomas Sing"], publisher: "Kosmos",
    mechanics: ["Cooperative Play", "Trick-taking", "Hidden Information"],
    categories: ["Cooperative", "Card Game"] },
  { title: "Sushi Go!", year: 2013, minPlayers: 2, maxPlayers: 5, playTime: 15, complexity: 1.1,
    description: "A fast-playing sushi-themed card drafting game — pick a card, pass the rest, and build a tasty set.",
    designers: ["Phil Walker-Harding"], publisher: "Gamewright",
    mechanics: ["Drafting", "Set Collection"],
    categories: ["Family", "Card Game"] },
  { title: "Kingdomino", year: 2016, minPlayers: 2, maxPlayers: 4, playTime: 20, complexity: 1.2,
    description: "Draft domino tiles to build the most valuable kingdom, balancing greed against turn order.",
    designers: ["Bruno Cathala"], publisher: "Blue Orange Games",
    mechanics: ["Tile Placement", "Drafting"],
    categories: ["Family", "Abstract Strategy"] },
  { title: "Five Tribes", year: 2014, minPlayers: 2, maxPlayers: 4, playTime: 80, complexity: 3.0,
    description: "Move meeples like Mancala pieces across a sultanate to trigger powerful tile effects.",
    designers: ["Bruno Cathala"], publisher: "Days of Wonder",
    mechanics: ["Worker Placement", "Set Collection", "Route Building"],
    categories: ["Strategy"] },
  { title: "Coimbra", year: 2018, minPlayers: 2, maxPlayers: 4, playTime: 90, complexity: 3.2,
    description: "Roll and draft dice to secure the favour of historical Portuguese figures.",
    designers: ["Flaminia Brasini", "Virginio Gigli", "Stefano Luperto"], publisher: "eggertspiele",
    mechanics: ["Dice Rolling", "Drafting", "Set Collection"],
    categories: ["Strategy"] },
  { title: "Great Western Trail", year: 2016, minPlayers: 2, maxPlayers: 4, playTime: 150, complexity: 3.7,
    description: "Drive cattle from Texas to Kansas City, building an engine of railway and building upgrades along the way.",
    designers: ["Alexander Pfister"], publisher: "eggertspiele",
    mechanics: ["Route Building", "Engine Building", "Hand Management"],
    categories: ["Strategy", "Economic"] },
  { title: "Isle of Skye", year: 2015, minPlayers: 1, maxPlayers: 5, playTime: 50, complexity: 2.6,
    description: "Buy and sell your own tiles simultaneously while building the most valuable Scottish isle.",
    designers: ["Alexander Pfister", "Andreas Pelikan"], publisher: "Lookout Games",
    mechanics: ["Tile Placement", "Auction/Bidding"],
    categories: ["Strategy", "Abstract Strategy"] },
];

// Demo "players" and the ratings/ownership that drive the recommendation engine.
const players = [
  { name: "Amara", bio: "Loves cooperative games and a good engine.",
    rated: [["Pandemic", 5], ["Spirit Island", 5], ["Wingspan", 4], ["Hanabi", 4], ["The Crew: The Quest for Planet Nine", 5]],
    owns: ["Pandemic", "Spirit Island", "Wingspan"] },
  { name: "Diego", bio: "Euro-economy obsessive; will worker-place anything.",
    rated: [["Agricola", 5], ["Caverna", 5], ["Great Western Trail", 5], ["Puerto Rico", 4], ["Concordia", 4]],
    owns: ["Agricola", "Great Western Trail", "Puerto Rico"] },
  { name: "Priya", bio: "Plays fast party games on weeknights, heavier stuff on weekends.",
    rated: [["Codenames", 5], ["Sushi Go!", 4], ["Dixit", 4], ["Splendor", 4], ["Azul", 5]],
    owns: ["Codenames", "Sushi Go!", "Azul"] },
  { name: "Tomasz", bio: "Deck-builder and card-drafter at heart.",
    rated: [["Dominion", 5], ["Star Realms", 5], ["Clank!", 4], ["7 Wonders", 4], ["Century: Spice Road", 4]],
    owns: ["Dominion", "Star Realms", "Clank!"] },
  { name: "Nadia", bio: "Heavy-euro and area-control fan; the bigger the box the better.",
    rated: [["Brass: Birmingham", 5], ["Root", 5], ["Scythe", 5], ["Terraforming Mars", 4], ["Gloomhaven", 5]],
    owns: ["Brass: Birmingham", "Root", "Scythe"] },
  { name: "Ben", bio: "New to the hobby, started with gateway games.",
    rated: [["Catan", 4], ["Ticket to Ride", 5], ["Carcassonne", 4], ["Kingdomino", 4], ["Patchwork", 5]],
    owns: ["Catan", "Ticket to Ride", "Kingdomino"] },
];

module.exports = { games, players };
